# Dependencies
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title:            Staged
tagline:          'A Staphylococcus aureus genomics blog.'
description:      'Latest updates on research into <em>Staphylococcus aureus</em> genomics.'
url:              http://staged-blog.github.io
baseurl:          /

author:
  name:           'Robert Petit'
  url:            https://twitter.com/rpetit3

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/staged-blog/staged-blog.github.io
